/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
//Base Address for RCC and GPIO
#define RCC_BASE     0x40021000
#define GPIOA_BASE   0x40010800

//Register in Module CRH and ODR
//CRH --> MODE
//ODR --> PUT 1 FOR I/P
#define RCC_APB2ENR  *(volatile uint32_t *)(RCC_BASE   + 0X18)
#define GPIOA_CRH    *(volatile uint32_t *)(GPIOA_BASE + 0X04)
#define GPIOA_ODR    *(volatile uint32_t *)(GPIOA_BASE + 0X0C)




int main(void)
{

	//PUT IN APB2ENR REG 1 IN BIT.2
	RCC_APB2ENR =1<<2;
	//MODE BIT
	GPIOA_CRH &=0XFF0FFFFF;
	GPIOA_CRH |=0X00200000;
    while(1)
    {
	//ON BIT.13 IN ODR REG
	GPIOA_ODR |=1<<13;    //TO BIT
	//DELARY
	for (int i=0; i<5000;i++);
	GPIOA_ODR &=~(1<<13);//TO CLEAR
	for (int i =0;i<5000;i++);
    }



  return 0;

}
